<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>snow</string>
	</array>
	<key>name</key>
	<string>SnowScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.snow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\bclass +([A-Z][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;-</string>
			<key>name</key>
			<string>keyword.operator.snow</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.snow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.snow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-z0-9_]+) *\(([^\)]*)\)</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.snow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.snow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([A-Z][A-Za-z0-9_]*) *\(([^\)]*)\)</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.snow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\bfn +([a-z0-9_]+) *$</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfn\b</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.snow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Z][A-Za-z0-9_]*)\.\.</string>
			<key>name</key>
			<string>keyword.operator.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\.=\+\-*/&lt;&gt;,]</string>
			<key>name</key>
			<string>keyword.operator.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bparent\b</string>
			<key>name</key>
			<string>storage.type.class.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\(\)]</string>
			<key>name</key>
			<string>keyword.operator.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(or|and|not|mod)\b</string>
			<key>name</key>
			<string>keyword.operator.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|elif|else|for|while|in)\b</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(die|echo)\b</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.snow</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{[^\}]*\}</string>
					<key>name</key>
					<string>constant.language.boolean.false.snow</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.snow</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.snow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>extends +([A-Z][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>keyword.operator.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#[^$]*$</string>
			<key>name</key>
			<string>comment.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bto\b</string>
			<key>name</key>
			<string>keyword.source.snow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.snow</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.snow</string>
	<key>uuid</key>
	<string>d5a82620-3a9b-4d73-ad05-f1032f5bf137</string>
</dict>
</plist>
